function Icon({ name, className = "" }: { name: string; className?: string }) {
  const paths: Record<string, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>,
    folder: <path d="M3 7.5A2.5 2.5 0 0 1 5.5 5H10l2 2h6.5A2.5 2.5 0 0 1 21 9.5v8a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 17.5v-10Z" />,
    file: <><path d="M6 3h8l4 4v14H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z" /><path d="M14 3v5h5M8 13h8M8 17h6" /></>,
    chart: <><path d="M4 19V5M4 19h16" /><path d="m7 15 4-4 3 2 5-6" /></>,
    settings: <><circle cx="12" cy="12" r="3" /><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V20.3h-3v-.08A1.7 1.7 0 0 0 10.68 18.66a1.7 1.7 0 0 0-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 7.02 15 1.7 1.7 0 0 0 5.46 14H5.4v-3h.06A1.7 1.7 0 0 0 7.02 10a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.12-2.12.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 11.7 4.78V4.7h3v.08a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.12 2.12-.06.06A1.7 1.7 0 0 0 19.4 10 1.7 1.7 0 0 0 20.96 11H21v3h-.04A1.7 1.7 0 0 0 19.4 15Z" /></>,
    search: <><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4 4" /></>,
    bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4" /></>,
    user: <><circle cx="12" cy="8" r="3" /><path d="M5 20a7 7 0 0 1 14 0" /></>,
    lock: <><rect x="5" y="10" width="14" height="11" rx="2" /><path d="M8 10V7a4 4 0 0 1 8 0v3M12 14v3" /></>,
    down: <path d="m7 10 5 5 5-5" />,
  };
  return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function Toggle({ label, description, enabled = true }: { label: string; description: string; enabled?: boolean }) {
  return <div className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-semibold text-slate-700">{label}</p><p className="mt-1 text-xs text-slate-500">{description}</p></div><button type="button" aria-label={`${label}: ${enabled ? "on" : "off"}`} aria-pressed={enabled} className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${enabled ? "bg-blue-600" : "bg-slate-200"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${enabled ? "left-6" : "left-1"}`} /></button></div>;
}

export default function SettingsPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-800">
      <aside className="fixed inset-y-0 left-0 z-20 hidden w-64 flex-col border-r border-slate-200 bg-white px-4 py-6 lg:flex"><div className="mb-10 flex items-center gap-3 px-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 text-sm font-bold text-white">S</div><div><p className="text-base font-bold tracking-tight text-slate-900">SIH PS 107</p><p className="text-xs text-slate-400">Portal Dashboard</p></div></div><nav className="space-y-1">{[["Dashboard", "grid", "/"], ["Applications / Cases", "folder", "/applications-cases"], ["Reports", "file", "/reports-analytics"], ["Analytics", "chart", "/reports-analytics"], ["Settings", "settings", "/settings"]].map(([label, icon, href]) => <a key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition-colors ${label === "Settings" ? "bg-blue-50 text-blue-700" : "text-slate-500 hover:bg-slate-50 hover:text-slate-800"}`}><Icon name={icon} className="h-5 w-5" />{label}</a>)}</nav><div className="mt-auto rounded-2xl bg-slate-900 p-4 text-white"><p className="text-sm font-semibold">Need assistance?</p><p className="mt-1 text-xs leading-5 text-slate-300">Get help from the SIH support team.</p><button className="mt-3 text-xs font-semibold text-blue-300">Contact support →</button></div></aside>

      <div className="lg:pl-64"><header className="sticky top-0 z-10 flex h-20 items-center justify-between border-b border-slate-200 bg-white/95 px-5 backdrop-blur sm:px-8"><div className="flex items-center gap-3 lg:hidden"><div className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 text-sm font-bold text-white">S</div><span className="font-bold text-slate-900">SIH PS 107</span></div><div className="relative hidden w-full max-w-md lg:block"><Icon name="search" className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input aria-label="Search cases or data" placeholder="Search cases or data..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50" /></div><div className="flex items-center gap-3"><button aria-label="Notifications" className="relative rounded-xl p-2.5 text-slate-500 hover:bg-slate-100"><Icon name="bell" className="h-5 w-5" /><span className="absolute right-2.5 top-2.5 h-2 w-2 rounded-full border-2 border-white bg-rose-500" /></button><div className="hidden h-8 w-px bg-slate-200 sm:block" /><button className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-slate-50"><div className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-violet-500 text-xs font-bold text-white">PK</div><span className="hidden text-left sm:block"><span className="block text-sm font-semibold text-slate-700">Pushpit Kumar</span><span className="block text-xs text-slate-400">Administrator</span></span><Icon name="down" className="hidden h-4 w-4 text-slate-400 sm:block" /></button></div></header>

        <main className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><div className="mb-8"><p className="text-sm font-medium text-blue-600">Portal configuration</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">Settings</h1><p className="mt-1 text-sm text-slate-500">Manage your profile, preferences, and account security.</p></div>

          <div className="grid gap-7 xl:grid-cols-[minmax(0,1.15fr)_minmax(340px,0.85fr)]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between border-b border-slate-100 pb-5"><div><h2 className="font-bold text-slate-900">Profile</h2><p className="mt-1 text-sm text-slate-500">Your administrator account details.</p></div><button className="rounded-xl border border-slate-200 px-3.5 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">Edit Profile</button></div><div className="mt-6 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-violet-500 text-lg font-bold text-white">PK</div><div><p className="text-base font-bold text-slate-900">Pushpit Kumar</p><p className="text-sm text-slate-500">Administrator</p></div></div><dl className="mt-6 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs font-medium uppercase tracking-wide text-slate-400">Name</dt><dd className="mt-1 text-sm font-semibold text-slate-700">Pushpit Kumar</dd></div><div><dt className="text-xs font-medium uppercase tracking-wide text-slate-400">Role</dt><dd className="mt-1 text-sm font-semibold text-slate-700">Administrator</dd></div><div className="sm:col-span-2"><dt className="text-xs font-medium uppercase tracking-wide text-slate-400">Email</dt><dd className="mt-1 text-sm font-semibold text-slate-700">pushpit.kumar@example.com</dd></div></dl></section>

          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="border-b border-slate-100 pb-4"><h2 className="font-bold text-slate-900">Notification Preferences</h2><p className="mt-1 text-sm text-slate-500">Choose which portal updates you receive.</p></div><div className="divide-y divide-slate-100"><Toggle label="Case updates" description="When a case status or detail changes." /><Toggle label="Assignment notifications" description="When a case is assigned to you." /><Toggle label="Alert notifications" description="For cases requiring attention." enabled={false} /></div></section></div>

          <div className="mt-7 grid gap-7 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="border-b border-slate-100 pb-4"><h2 className="font-bold text-slate-900">Application Preferences</h2><p className="mt-1 text-sm text-slate-500">Customize how information appears in the portal.</p></div><div className="mt-5 space-y-5"><label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">Default dashboard view</span><select className="w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm text-slate-600 outline-none focus:border-blue-400"><option>Overview</option><option>Applications / Cases</option><option>Reports &amp; Analytics</option></select></label><label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">Date format</span><select className="w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm text-slate-600 outline-none focus:border-blue-400"><option>MMM D, YYYY · May 24, 2024</option><option>DD/MM/YYYY · 24/05/2024</option><option>YYYY-MM-DD · 2024-05-24</option></select></label><label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">Language</span><select className="w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm text-slate-600 outline-none focus:border-blue-400"><option>English</option><option>Hindi</option><option>Kannada</option></select></label></div></section>

          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="border-b border-slate-100 pb-4"><h2 className="font-bold text-slate-900">Security</h2><p className="mt-1 text-sm text-slate-500">Review account security and access details.</p></div><div className="mt-5 flex items-start gap-4 rounded-xl bg-slate-50 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-slate-500"><Icon name="lock" className="h-5 w-5" /></div><div><p className="text-sm font-semibold text-slate-700">Password</p><p className="mt-1 text-xs text-slate-500">Keep your account protected with a strong password.</p><button className="mt-3 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">Change Password</button></div></div><div className="mt-5 border-t border-slate-100 pt-5"><p className="text-sm font-semibold text-slate-700">Last login</p><p className="mt-1 text-sm text-slate-500">May 27, 2024 at 09:14 AM</p><p className="mt-1 text-xs text-slate-400">Mock account activity · Bengaluru, India</p></div></section></div>

          <div className="mt-7 flex flex-col justify-between gap-3 rounded-2xl border border-blue-100 bg-blue-50/60 p-5 sm:flex-row sm:items-center sm:px-6"><div><p className="text-sm font-semibold text-slate-800">Settings are for demonstration only</p><p className="mt-1 text-xs text-slate-500">Changes are not saved and no backend functionality is connected yet.</p></div><button className="w-fit rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Save Preferences</button></div>
        </main>
      </div>
    </div>
  );
}
