function Icon({ name, className = "" }: { name: string; className?: string }) {
  const paths: Record<string, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>,
    folder: <path d="M3 7.5A2.5 2.5 0 0 1 5.5 5H10l2 2h6.5A2.5 2.5 0 0 1 21 9.5v8a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 17.5v-10Z" />,
    file: <><path d="M6 3h8l4 4v14H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z" /><path d="M14 3v5h5M8 13h8M8 17h6" /></>,
    chart: <><path d="M4 19V5M4 19h16" /><path d="m7 15 4-4 3 2 5-6" /></>,
    settings: <><circle cx="12" cy="12" r="3" /><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.12 2.12-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V20.3h-3v-.08A1.7 1.7 0 0 0 10.68 18.66a1.7 1.7 0 0 0-1.88.34l-.06.06-2.12-2.12.06-.06A1.7 1.7 0 0 0 7.02 15 1.7 1.7 0 0 0 5.46 14H5.4v-3h.06A1.7 1.7 0 0 0 7.02 10a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.12-2.12.06.06a1.7 1.7 0 0 0 1.88.34A1.7 1.7 0 0 0 11.7 4.78V4.7h3v.08a1.7 1.7 0 0 0 1.03 1.56 1.7 1.7 0 0 0 1.88-.34l.06-.06 2.12 2.12-.06.06A1.7 1.7 0 0 0 19.4 10 1.7 1.7 0 0 0 20.96 11H21v3h-.04A1.7 1.7 0 0 0 19.4 15Z" /></>,
    search: <><circle cx="11" cy="11" r="6.5" /><path d="m16 16 4 4" /></>,
    bell: <><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9ZM10 21h4" /></>,
    arrow: <path d="M5 12h14M13 6l6 6-6 6" />,
    down: <path d="m7 10 5 5 5-5" />,
    back: <path d="m15 18-6-6 6-6" />,
    check: <path d="m5 12 4 4L19 6" />,
    user: <><circle cx="12" cy="8" r="3" /><path d="M5 20a7 7 0 0 1 14 0" /></>,
    edit: <><path d="m4 16-.8 4.8L8 20l11-11a2.8 2.8 0 0 0-4-4L4 16Z" /><path d="m13.5 6.5 4 4" /></>,
    plus: <><path d="M12 5v14M5 12h14" /></>,
  };
  return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

const timeline = [
  { title: "Case created", detail: "Submitted through the SIH public-service portal", date: "May 24, 2024 · 09:42 AM", color: "bg-blue-500", done: true },
  { title: "Assigned to Anita Sharma", detail: "Assigned by the case administration team", date: "May 24, 2024 · 11:15 AM", color: "bg-violet-500", done: true },
  { title: "Under review", detail: "Initial review and field requirements are in progress", date: "May 25, 2024 · 10:30 AM", color: "bg-amber-500", done: true },
  { title: "Latest update", detail: "Site assessment documents requested from applicant", date: "May 27, 2024 · 03:20 PM", color: "bg-slate-300", done: false },
];

export default function CaseDetailsPage() {
  return (
    <div className="min-h-screen bg-slate-50 text-slate-800">
      <aside className="fixed inset-y-0 left-0 z-20 hidden w-64 flex-col border-r border-slate-200 bg-white px-4 py-6 lg:flex">
        <div className="mb-10 flex items-center gap-3 px-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 text-sm font-bold text-white">S</div><div><p className="text-base font-bold tracking-tight text-slate-900">SIH PS 107</p><p className="text-xs text-slate-400">Portal Dashboard</p></div></div>
        <nav className="space-y-1">{[["Dashboard", "grid", "/"], ["Applications / Cases", "folder", "/applications-cases"], ["Reports", "file", "#"], ["Analytics", "chart", "#"], ["Settings", "settings", "#"]].map(([label, icon, href]) => <a key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition-colors ${label === "Applications / Cases" ? "bg-blue-50 text-blue-700" : "text-slate-500 hover:bg-slate-50 hover:text-slate-800"}`}><Icon name={icon} className="h-5 w-5" />{label}</a>)}</nav>
        <div className="mt-auto rounded-2xl bg-slate-900 p-4 text-white"><p className="text-sm font-semibold">Need assistance?</p><p className="mt-1 text-xs leading-5 text-slate-300">Get help from the SIH support team.</p><button className="mt-3 text-xs font-semibold text-blue-300">Contact support →</button></div>
      </aside>

      <div className="lg:pl-64">
        <header className="sticky top-0 z-10 flex h-20 items-center justify-between border-b border-slate-200 bg-white/95 px-5 backdrop-blur sm:px-8"><div className="flex items-center gap-3 lg:hidden"><div className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 text-sm font-bold text-white">S</div><span className="font-bold text-slate-900">SIH PS 107</span></div><div className="relative hidden w-full max-w-md lg:block"><Icon name="search" className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input aria-label="Search cases or data" placeholder="Search cases or data..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-50" /></div><div className="flex items-center gap-3"><button aria-label="Notifications" className="relative rounded-xl p-2.5 text-slate-500 hover:bg-slate-100"><Icon name="bell" className="h-5 w-5" /><span className="absolute right-2.5 top-2.5 h-2 w-2 rounded-full border-2 border-white bg-rose-500" /></button><div className="hidden h-8 w-px bg-slate-200 sm:block" /><button className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-slate-50"><div className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-blue-500 to-violet-500 text-xs font-bold text-white">PK</div><span className="hidden text-left sm:block"><span className="block text-sm font-semibold text-slate-700">Pushpit Kumar</span><span className="block text-xs text-slate-400">Administrator</span></span><Icon name="down" className="hidden h-4 w-4 text-slate-400 sm:block" /></button></div></header>

        <main className="mx-auto max-w-7xl px-5 py-8 sm:px-8">
          <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><a href="/applications-cases" className="mb-3 inline-flex items-center gap-1.5 text-sm font-medium text-slate-500 hover:text-blue-600"><Icon name="back" className="h-4 w-4" />Back to Applications / Cases</a><p className="text-sm font-medium text-blue-600">Case management</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">Case Details</h1><p className="mt-1 text-sm text-slate-500">Review the details and current progress of this case.</p></div><div className="flex items-center gap-2"><span className="rounded-full bg-rose-50 px-3 py-1.5 text-xs font-semibold text-rose-700">High priority</span><span className="rounded-full bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700">In Progress</span></div></div>

          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div className="flex items-start gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon name="folder" className="h-6 w-6" /></div><div><p className="text-xs font-semibold uppercase tracking-wide text-blue-600">SIH-2024-0187</p><h2 className="mt-1 text-xl font-bold text-slate-900">Smart irrigation monitoring</h2><p className="mt-1 text-sm text-slate-500">Applicant: Department of Agriculture · Mock case record</p></div></div><div className="grid grid-cols-2 gap-x-8 gap-y-4 sm:grid-cols-4 lg:min-w-[600px]"><div><p className="text-xs text-slate-400">Category</p><p className="mt-1 text-sm font-semibold text-slate-700">Agriculture</p></div><div><p className="text-xs text-slate-400">Date submitted</p><p className="mt-1 text-sm font-semibold text-slate-700">May 24, 2024</p></div><div><p className="text-xs text-slate-400">Assigned officer</p><p className="mt-1 text-sm font-semibold text-slate-700">Anita Sharma</p></div><div><p className="text-xs text-slate-400">Current status</p><p className="mt-1 text-sm font-semibold text-blue-700">In Progress</p></div></div></div></section>

          <div className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1.4fr)_minmax(320px,0.6fr)]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Case Overview</h2><p className="mt-1 text-sm text-slate-500">Key information for the assigned officer.</p></div><span className="text-xs font-medium text-slate-400">Sample data</span></div><dl className="mt-6 divide-y divide-slate-100"><div className="grid gap-2 py-4 sm:grid-cols-[150px_1fr]"><dt className="text-sm font-semibold text-slate-600">Description</dt><dd className="text-sm leading-6 text-slate-500">The applicant has requested support to deploy a smart irrigation monitoring system across three community farming clusters. The proposed solution will help track soil moisture and optimize water usage.</dd></div><div className="grid gap-2 py-4 sm:grid-cols-[150px_1fr]"><dt className="text-sm font-semibold text-slate-600">Current situation</dt><dd className="text-sm leading-6 text-slate-500">Technical feasibility review is underway. Field teams have confirmed the target sites and are waiting for the initial assessment documents.</dd></div><div className="grid gap-2 py-4 sm:grid-cols-[150px_1fr]"><dt className="text-sm font-semibold text-slate-600">Required action</dt><dd className="text-sm leading-6 text-slate-500">Review the submitted site assessment, confirm eligibility, and schedule a field inspection with the district agriculture office.</dd></div><div className="grid gap-2 py-4 sm:grid-cols-[150px_1fr]"><dt className="text-sm font-semibold text-slate-600">Location</dt><dd className="text-sm leading-6 text-slate-500">Kolar district, Karnataka · Three community farming clusters</dd></div></dl></section>

          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="font-bold text-slate-900">Case Timeline</h2><p className="mt-1 text-sm text-slate-500">Activity history for this case.</p><div className="mt-6 space-y-6">{timeline.map((item, index) => <div key={item.title} className="relative flex gap-3">{index < timeline.length - 1 && <div className="absolute left-[5px] top-4 h-[calc(100%+8px)] w-px bg-slate-200" />}<span className={`relative mt-1 h-3 w-3 shrink-0 rounded-full border-2 border-white ${item.color} ring-1 ring-slate-200`} /><div className="-mt-1"><p className="text-sm font-semibold text-slate-700">{item.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{item.detail}</p><p className="mt-1 text-[11px] font-medium text-slate-400">{item.date}</p></div></div>)}</div></section></div>

          <section className="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-bold text-slate-900">Actions</h2><p className="mt-1 text-sm text-slate-500">Mock controls for managing this case.</p></div><div className="grid gap-2 sm:grid-cols-4"><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700"><Icon name="edit" className="h-4 w-4" />Update Status</button><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700"><Icon name="user" className="h-4 w-4" />Assign Officer</button><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700"><Icon name="plus" className="h-4 w-4" />Add Update</button><a href="/applications-cases" className="inline-flex items-center justify-center rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Back to Cases</a></div></div></section>
        </main>
      </div>
    </div>
  );
}
